add pattern refresh feature
update an old pattern in an already existing git ignore file

Signed-off-by: Eric Villard <dev@eviweb.fr>

diff --git a/git-ignore-refresh b/git-ignore-refresh
--- a/git-ignore-refresh
+++ b/git-ignore-refresh
@@ -1,18 +1,18 @@
 #! /bin/bash
 # The MIT License
-# 
+#
 # Copyright 2013 Eric VILLARD <dev@eviweb.fr>.
-# 
+#
 # Permission is hereby granted, free of charge, to any person obtaining a copy
 # of this software and associated documentation files (the "Software"), to deal
 # in the Software without restriction, including without limitation the rights
 # to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 # copies of the Software, and to permit persons to whom the Software is
 # furnished to do so, subject to the following conditions:
-# 
+#
 # The above copyright notice and this permission notice shall be included in
 # all copies or substantial portions of the Software.
-# 
+#
 # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 # IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 # FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
@@ -22,31 +22,45 @@
 # THE SOFTWARE.
 
 usage() {
-	echo "usage: git ignore <subcommand>"
-	echo
-	echo "Available subcommands are:"
-	echo "  list        Lists all available ignore patterns."
-    echo "  see         Displays the content of one or more patterns."
-	echo "  create      Creates a git ignore file."
-    echo "  remove      Removes a git ignore file."
-	echo "  add         Adds ignore patterns to an existing ignore file."
-	echo "  delete      Deletes ignore patterns from an existing ignore file."
-    echo "  refresh     Refreshes already set ignore patterns in an existing ignore file."
-    echo "  update      Update this tool and its submodules to their last up to date version."
-    echo "  register    Register local gitignore pattern repository"
-    echo "  unregister  Register local gitignore pattern repository"
-	echo "  help        Displays this message."
-	echo "  version     Shows version information."
-	echo
-	echo "Try 'git ignore <subcommand> help' for details."
+    echo "usage: git ignore refresh <file> <pattern1>[,<pattern2>,...]"
+    echo ""
+    echo "Mandatory Parameters :"
+    echo "  <file>                      .gitignore file"
+    echo "  <pattern1>[,<pattern2>,...] comma separated list of patterns to refresh"
+    echo ""
+    echo "Patterns are the ones listed by the list subcommand and are case sensitive"
+    echo ""
+}
+
+parse_args() {
+    # parse options
+    FLAGS "$@" || exit $?
+    eval set -- "${FLAGS_ARGV}"
+
+    # save file and patterns in a global variable
+    FILE=$1
+    PATTERNS=$2
 }
 
 cmd_default() {
-	usage
-	exit 0
+    cmd_delete "$@"
+}
+
+cmd_delete() {
+    parse_args "$@"
+
+    if [[ ! -f $FILE ]]; then
+        echo "File not found : $FILE"
+        exit 1
+    fi
+
+    declare -a patterns=( $(splitpatterns "$PATTERNS") )
+    for pattern in "${patterns[@]}"; do
+        refreshpatternsinfile $pattern $FILE
+    done
 }
 
 cmd_help() {
-	usage
-	exit 0
+    usage
+    exit 0
 }
