add view command
to display the content of a given file

Signed-off-by: Eric Villard <dev@eviweb.fr>

diff --git a/git-ignore-view b/git-ignore-view
--- a/git-ignore-view
+++ b/git-ignore-view
@@ -23,34 +23,41 @@
 
 usage() {
     echo ""
-    echo "Git ignore help"
+    echo "Display the content of an existing git ignore file."
     echo ""
-	echo "usage: git ignore <subcommand>"
-	echo
-	echo "Available subcommands are:"
-	echo "  list        List all available ignore patterns."
-    echo "  see         Display the content of one or more patterns."
-	echo "  create      Create a git ignore file."
-    echo "  remove      Remove a git ignore file."
-	echo "  add         Add ignore patterns to an existing ignore file."
-	echo "  delete      Delete ignore patterns from an existing ignore file."
-    echo "  refresh     Refresh some already set ignore patterns in an existing ignore file."
-    echo "  update      Update this tool and its submodules to their last up to date version."
-    echo "  register    Register a local gitignore pattern repository."
-    echo "  unregister  Unregister a local gitignore pattern repository."
-    echo "  view        Display the content of an existing git ignore file."
-	echo "  help        Display this message."
-	echo "  version     Display version information."
-	echo
-	echo "Try 'git ignore <subcommand> help' for details."
+    echo "usage: git ignore view <file>"
+    echo ""
+    echo "Mandatory Parameters :"
+    echo "  <file>                      .gitignore file"
+    echo ""
+}
+
+parse_args() {
+    # parse options
+    FLAGS "$@" || exit $?
+    eval set -- "${FLAGS_ARGV}"
+
+    # save file in a global variable
+    FILE=$1
 }
 
 cmd_default() {
-	usage
-	exit 0
+    cmd_view "$@"
+}
+
+cmd_view() {
+    parse_args "$@"
+
+    if [[ ! -f $FILE ]]; then
+        echo "File not found : $FILE"
+        exit 1
+    fi
+
+    cat $FILE
+    echo ""
 }
 
 cmd_help() {
-	usage
-	exit 0
+    usage
+    exit 0
 }
